# Workflow name show in github
name: Aplha

# Controls when the action will run. 
# Triggers the workflow on push or pull request events but only for the main branch
on:
  push:
    branches: 
      - alpha
  pull_request:
    branches: 
      - alpha

env:
  SAMPLE_PATH: codebase/android

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This job builds the project
  build:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Timeout for the job
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # To checkout repository
    - uses: actions/checkout@v2

    # Java setup
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    # File permission changes for gradle scripts
    - name: Grant execute permission for gradlew
      run: chmod +x ./${{ env.SAMPLE_PATH }}/gradlew

    # Build project
    - name: Build with Gradle
      working-directory: ${{ env.SAMPLE_PATH }}
      run: ./gradlew assembleDebug --stacktrace
      
    # Upload APK files
    - name: Upload build outputs (APKs)
      uses: actions/upload-artifact@v2
      with:
        name: build-outputs
        path: ${{ env.SAMPLE_PATH }}/app/build/outputs
